[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20.12.2"
  # Optionnel si besoin de contourner des peer-deps :
  # NPM_FLAGS = "--legacy-peer-deps"
