[build]
  command = "npm run build || true"
  publish = ".next"
  ignore = "git diff --quiet HEAD^ HEAD ."

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  
# Variables d'environnement (à configurer dans l'UI Netlify aussi)
[context.production.environment]
  NEXT_PUBLIC_SUPABASE_URL = "votre_url_supabase"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "votre_key_supabase"

# Redirection des routes Next.js
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200